//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileBook.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfileBook.Resx.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Profile.
        /// </summary>
        internal static string AddProfileTitlePage {
            get {
                return ResourceManager.GetString("AddProfileTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName and Name fields must be filled.
        /// </summary>
        internal static string ALERT_ADD_EDIT_PROFILE {
            get {
                return ResourceManager.GetString("ALERT_ADD_EDIT_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!! Account created.
        /// </summary>
        internal static string AUTHETICATION_SUCCESS {
            get {
                return ResourceManager.GetString("AUTHETICATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CONFIRM_CANCEL {
            get {
                return ResourceManager.GetString("CONFIRM_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CONFIRM_OK {
            get {
                return ResourceManager.GetString("CONFIRM_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Color Theme.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string DarkThemeOff {
            get {
                return ResourceManager.GetString("DarkThemeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string DarkThemeOn {
            get {
                return ResourceManager.GetString("DarkThemeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you really want to delete this profile?.
        /// </summary>
        internal static string DELETE_PROFILE_QUESTION {
            get {
                return ResourceManager.GetString("DELETE_PROFILE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteContextAction {
            get {
                return ResourceManager.GetString("DeleteContextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditContextAction {
            get {
                return ResourceManager.GetString("EditContextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string EditProfileTitlePage {
            get {
                return ResourceManager.GetString("EditProfileTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open gallery.
        /// </summary>
        internal static string GET_IMAGE_ACTION {
            get {
                return ResourceManager.GetString("GET_IMAGE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose action.
        /// </summary>
        internal static string IMAGE_PROFILE_ACTION {
            get {
                return ResourceManager.GetString("IMAGE_PROFILE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login. Login must be from 4 to 16 characters and must not start with a number.
        /// </summary>
        internal static string INVALID_LOGIN {
            get {
                return ResourceManager.GetString("INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password!.
        /// </summary>
        internal static string INVALID_LOGIN_OR_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_LOGIN_OR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password. Password must be from 8 to 16 characters, must contain at least one uppercase letter, one lowercase and one number.
        /// </summary>
        internal static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login is already taken. Come up with another.
        /// </summary>
        internal static string LOGIN_TAKEN {
            get {
                return ResourceManager.GetString("LOGIN_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        internal static string LogOutToolbarItem {
            get {
                return ResourceManager.GetString("LogOutToolbarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main List.
        /// </summary>
        internal static string MainListTitlePage {
            get {
                return ResourceManager.GetString("MainListTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        internal static string NicknameText {
            get {
                return ResourceManager.GetString("NicknameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles added.
        /// </summary>
        internal static string NoProfilesLabel {
            get {
                return ResourceManager.GetString("NoProfilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords mismatch. Re-enter passwords.
        /// </summary>
        internal static string PASSWORD_MISMATCH {
            get {
                return ResourceManager.GetString("PASSWORD_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date creation.
        /// </summary>
        internal static string RadioCreation {
            get {
                return ResourceManager.GetString("RadioCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RadioName {
            get {
                return ResourceManager.GetString("RadioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        internal static string RadioNickName {
            get {
                return ResourceManager.GetString("RadioNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveToolbatItem {
            get {
                return ResourceManager.GetString("SaveToolbatItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitlePage {
            get {
                return ResourceManager.GetString("SettingsTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsToolbarItem {
            get {
                return ResourceManager.GetString("SettingsToolbarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users SignIn.
        /// </summary>
        internal static string SignInTitlePage {
            get {
                return ResourceManager.GetString("SignInTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string SignUpButtonText {
            get {
                return ResourceManager.GetString("SignUpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users SignUp.
        /// </summary>
        internal static string SignUpTitlePage {
            get {
                return ResourceManager.GetString("SignUpTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort list by.
        /// </summary>
        internal static string SortListLabel {
            get {
                return ResourceManager.GetString("SortListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open camera.
        /// </summary>
        internal static string TAKE_IMAGE_ACTION {
            get {
                return ResourceManager.GetString("TAKE_IMAGE_ACTION", resourceCulture);
            }
        }
    }
}
